name: CI Pipeline

on:
  push:
    branches:
      - fix-api-t
      - main
      - staging

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Create .env file
      run: |
        echo DB_URL=${{ secrets.DB_URL }} >> .env
        echo DB_URL_TEST=${{ secrets.DB_URL_TEST }} >> .env
        echo NODE_ENV=${{ secrets.NODE_ENV }} >> .env

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Lint code
      run: npm run lint

    - name: Run tests
      run: npm test

    - name: Run database migrations
      run: npm run migrate

    - name: Build project
      run: npm run build

    - name: Deploy to staging
      if: github.ref == 'refs/heads/staging'
      run: npm run deploy:staging

    - name: Deploy to production
      if: github.ref == 'refs/heads/main'
      run: npm run deploy:production
